name = "tcmcdss"
compatibility_date = "2024-01-01"
pages_build_output_dir = "frontend"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "tcmcdss-db"
database_id = "5598e403-7032-4ea5-b1ba-2592be0a5663"
